MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.09.26

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,16 +8,21 @@ osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=35
-    - CONDA_PY=36
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.5
+    - CONFIG=osx_python3.6
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "ZeVe4Arw6RrUryy4mjou8tJSwPQm//4qy5utZ+cuJ5cvuPZ95UZDayex8nXyoaWKuhSvYlvcZbjFDCS+1J/6k0P5cHA2i2KOW0OUBqJejD77mkBfRT8Vdg2fTef6DPyGPJPzKb9asE3nW/KbGIVg9jZ/9a/E2KgRRm0jEyI9GpbFBKYrhOhvMyULDRRuEh9YVdrbe8DGupApsCORNt2JrevkhW2OkiwdV8UA5XrMCHETZQe9SQFve9THluS0cNzVdUfaIE9TjuXlHeda5/eySDqE81c/qLbcpPfuUe3gt4K7DLWyjI614yGiX5xEHA6boVOFBFIOVjWhzKn+BDKR7JXTsiHPComP7tkb98xbPQbilIjemcWCF+z0/rjas7zR+ATdsmKHgWAyM1VPQYI9etHFWDTl8p/Rarjow0oNgyqJq+wDjEPkrC21DKBx2VKmN/S6oY+3FHTRWDmvLA4aDJe105OiCnTjYVg0Siu2H6N0ogysbSzowF4VqO44bwXGM5LPTnx47ulVpsqjX38gLc7e+gKEHegM18qJi9ezuMQI7UVNqIpBFvoRVtZMRBlCO0XIoQxpm8HXe8GLnD0pp+RbvWbmNqfdGEreTHM4xwpD9bJayBe9jbm9ygy2CLp6mCTcTLiKDaR3N8qsOYDBn95V31mCJkI6D/CS8yKYo5U="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
     - |
       echo ""
@@ -43,14 +48,18 @@ install:
       echo ""
       echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
